{% set name = "plyfile" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e9a18d22a3158fcd74df38761d43a7facc6df75126f2ab9f4e9a5d4d2188652

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - plyfile

about:
  home: https://github.com/dranjan/python-plyfile
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: NumPy-based text/binary PLY file reader/writer for Python
  dev_url: https://github.com/dranjan/python-plyfile

extra:
  recipe-maintainers:
    - mdraw
