{% set name = "plyfile" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a49bdf5285c95b6f7d4b9f2954b7867c44f8e13348606d886d8e0a561f6f4671

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - pdm-pep517 >=1.0.0
  run:
    - python >=3.8
    - numpy >=1.17

test:
  imports:
    - plyfile

about:
  home: https://github.com/dranjan/python-plyfile
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: NumPy-based text/binary PLY file reader/writer for Python
  dev_url: https://github.com/dranjan/python-plyfile

extra:
  recipe-maintainers:
    - mdraw
