travis:
  secure:
    BINSTAR_TOKEN: Zg4XtdP0VL1Sr1ySoW9tQ3jtVaXmWva8qBNJFqf4OdAC5Nntg1ge+dgIj6SfGyD04UQPlhL1ZTo1Ykn14MTPy2424lrrH6blYYmR0iHUGCMT6RY+ENqKDV4f4RGi/0obRSl+pu0X2kZOpjVkamHRVVoU/u4Yl6wLdD/EUnEBRod6iVW39LsNQySFhw1c8nQYOwZtjDwJDmuMFx//JnkpkVbeWJfT4UwuK7U2rURGLszDQ+qguMWzKUEfDqxq+kgA9DyXoh9oxr2SbBh9zArHx+3Zv1lDo9NYHPfLO1y80CoRMFOyhnPlZNwT9628c93JNdcPf0MOH8W4xDwx2V4YH05XqyRWqgqocGHNwpIoOT+X6wd8UoNuDoAsrAWswYB2FoZjdCCb2QirFAMg05bV76CFWZHNbnR2SnSUxwHTW3ICfjh+oMU/stt8cz7LnAXZG0d696kY4L8P6T9s1jBLfWa++hseQHKTYmPg/RHpYrxPIYWL0ptQt1kJcPffsAEMklH69NiZc4JXwM0GhxCALob2jqXadAQfsvsanIyNGXE1mIVvdiqQ5rzlV3CSUgW2JjCxxMf9DkLKyBUS50+cS7ofehArMCtQpjPoHOvuc+E7CUNhY6KXVokX4xHBWdJfouZcdmQ2eaWO7Cc2xzThWTr6bMJUAQkE2eYPXLTHPnA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
